In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [7]:
b = np.arange(10).reshape(5,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
np.ndim(b)

2

In [9]:
c= np.array([2*i for i in range(1,10)])
print(c)

[ 2  4  6  8 10 12 14 16 18]


In [16]:
d = np.linspace(0,25,6)
print(d)
print(d[:, np.newaxis])

[ 0.  5. 10. 15. 20. 25.]
[[ 0.]
 [ 5.]
 [10.]
 [15.]
 [20.]
 [25.]]


In [24]:
from scipy import sparse

X = np.random.random((10,5))
X[X < 0.85] = 0
X_csr = sparse.csr_matrix(X)

print(X)

print(X_csr)

[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.87279481 0.         0.88219337]
 [0.         0.         0.         0.         0.90876251]
 [0.9931348  0.         0.         0.         0.        ]
 [0.90632589 0.         0.         0.         0.        ]
 [0.         0.9749356  0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
  (2, 2)	0.8727948101852733
  (2, 4)	0.8821933703880097
  (3, 4)	0.9087625063749707
  (4, 0)	0.9931347993441261
  (5, 0)	0.9063258940474044
  (6, 1)	0.9749356036698672


In [27]:
e = np.random.randn(5, 10)
print(e)

[[ 1.15793709  0.20090012 -0.74602528  0.88279224  0.45497618  1.38849463
   1.86962132  0.76889007  0.36534959  1.59176597]
 [-0.15349566 -0.93263008  0.99391333  0.98904746 -0.49280213 -0.42540383
  -1.67235069  0.6240381   0.97085152  0.80614213]
 [-2.34791601  0.40305553  0.83342524  1.0139124   0.75092438  0.12110063
  -0.87538565 -0.51997612 -1.03032494 -0.25944016]
 [-0.63428537 -0.85942598  0.78328534  0.77224648 -1.12914993  0.00931375
  -0.0473344  -0.25550817 -0.68532407 -0.45509361]
 [ 0.4612779  -0.24934913  0.7654349  -0.58456608  0.80012752 -0.03714154
  -1.56009427 -0.77676275 -0.14049436  0.76631393]]


In [32]:
f = np.array([1.3, 1.5, 2.3, 2.5, 3.3, 3.5, 4.4, 4.5, 5.5, 6.5])
g = np.around(f).astype(int)

print(g)

[1 2 2 2 3 4 4 4 6 6]


In [38]:
h = (np.random.rand(4,5)*100).astype(int)
print(h)

[[74 70 60 16 10]
 [89 32 62 68 55]
 [25 56 65 31 68]
 [67 78 92 63 54]]


In [45]:
print(h[2:,:3])

[[25 56 65]
 [67 78 92]]
