In [30]:
import numpy as np
Q=np.zeros((21,4),dtype=int)

In [31]:
R=np.zeros((21,4),dtype=int)

In [32]:
v=0.9 # Factor de aprendizaje learning rate
y=0.8 # Factor de descuento discount factor

In [33]:
 # Tabla de transiciones
import pandas as pd
df= pd.read_csv("T.csv",header=None)
T=df.to_numpy()

for i, fila in enumerate(T):
    for j, elemento in enumerate(fila):
        # if(T[i,j]%5 == 0):
        #     R[i,j] = 50
        if(T[i,j] == 1):
            R[i,j] = 100
T

array([[-1, -1, -1, -1],
       [ 1, -1, -1, -1],
       [ 2,  1, -1, -1],
       [ 3,  2,  1, -1],
       [ 4,  3,  2,  1],
       [ 5,  4,  3,  2],
       [ 6,  5,  4,  3],
       [ 7,  6,  5,  4],
       [ 8,  7,  6,  5],
       [ 9,  8,  7,  6],
       [10,  9,  8,  7],
       [11, 10,  9,  8],
       [12, 11, 10,  9],
       [13, 12, 11, 10],
       [14, 13, 12, 11],
       [15, 14, 13, 12],
       [16, 15, 14, 13],
       [17, 16, 15, 14],
       [18, 17, 16, 15],
       [19, 18, 17, 16],
       [20, 19, 18, 17]], dtype=int64)

In [34]:
R

array([[  0,   0,   0,   0],
       [100,   0,   0,   0],
       [  0, 100,   0,   0],
       [  0,   0, 100,   0],
       [  0,   0,   0, 100],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [35]:
#Seleccionamos un estado al azar
J1_wins=0
J2_wins=0

turno=0
partida=0

s=20
while(partida<100000):
    a=np.random.randint(4)

    while(T[s,a] >= s):
        a=np.random.randint(4)

    if((partida%2 ==0 and turno%2 == 0) or (partida%2 !=0 and turno%2 != 0)):

        siguiente=T[s,a]
        Q[s,a]=(1-v)*Q[s,a]+v*(R[s,a]+y*max(Q[siguiente,]))
        # print ("Turno ",turno+1,"J1 -->",siguiente)
        if(siguiente == 1):
            J1_wins+=1
        elif(siguiente < 1):
            J2_wins+=1
    else:
        siguiente=T[s,a]
        # print ("Turno ",turno+1,"J2 -->",siguiente)
        if(siguiente == 1):
            J2_wins+=1
        elif(siguiente < 1):
            J1_wins+=1
    s = siguiente
    turno+=1
    if(siguiente <= 1):
        partida+=1
        turno=0
        s=20
print("Jugador uno ha ganado: ", J1_wins)
print("Jugador dos ha ganado: ", J2_wins)
    

Jugador uno ha ganado:  50212
Jugador dos ha ganado:  49788


In [36]:
Q

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, 99, 19, 19],
       [ 0, 79, 99, 19],
       [ 0, 79, 79, 99],
       [ 0, 79, 79, 79],
       [ 0, 63, 79, 79],
       [ 0, 63, 63, 79],
       [ 0, 63, 63, 63],
       [ 0, 50, 63, 63],
       [ 0, 50, 50, 63],
       [ 0, 50, 50, 50],
       [ 0, 39, 50, 50],
       [ 0, 39, 39, 50],
       [ 0, 39, 39, 39],
       [ 0, 31, 39, 39],
       [ 0, 31, 31, 39],
       [ 0, 31, 31, 31],
       [ 0, 24, 31, 31],
       [ 0, 24, 24, 31],
       [ 0, 24, 24, 24]])

In [37]:
J1_wins=0
J2_wins=0

turno=0
partida=0

s=20
while(partida<100000):
    a=np.random.randint(4)

    if(turno%2 == 0):
        siguiente=T[s,np.argmax(Q[s,])]
        # print ("Turno ",turno+1,"J1 -->",siguiente)
        if(siguiente == 1):
            J1_wins+=1
        elif(siguiente < 1):
            J2_wins+=1
    else:
        siguiente=T[s,a]
        # print ("Turno ",turno+1,"J2 -->",siguiente)
        if(siguiente == 1):
            J2_wins+=1
        elif(siguiente < 1):
            J1_wins+=1
    s = siguiente
    turno+=1
    if(siguiente <= 1):
        partida+=1
        turno=0
        s=20
print("Jugador uno ha ganado: ", J1_wins)
print("Jugador dos ha ganado: ", J2_wins)



Jugador uno ha ganado:  79975
Jugador dos ha ganado:  20025


In [39]:
for t in range(0,21):
 print ("estado:",t+1," accion:",np.argmax(Q[t,])+1, "valor:", T[t,np.argmax(Q[t,])])

estado: 1  accion: 1 valor: -1
estado: 2  accion: 1 valor: 1
estado: 3  accion: 2 valor: 1
estado: 4  accion: 3 valor: 1
estado: 5  accion: 4 valor: 1
estado: 6  accion: 2 valor: 4
estado: 7  accion: 3 valor: 4
estado: 8  accion: 4 valor: 4
estado: 9  accion: 2 valor: 7
estado: 10  accion: 3 valor: 7
estado: 11  accion: 4 valor: 7
estado: 12  accion: 2 valor: 10
estado: 13  accion: 3 valor: 10
estado: 14  accion: 4 valor: 10
estado: 15  accion: 2 valor: 13
estado: 16  accion: 3 valor: 13
estado: 17  accion: 4 valor: 13
estado: 18  accion: 2 valor: 16
estado: 19  accion: 3 valor: 16
estado: 20  accion: 4 valor: 16
estado: 21  accion: 2 valor: 19
