In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
b = np.array([[2+0j, 3+7j],[5+1j,4]],dtype=np.complex64)
print(b)

[[2.+0.j 3.+7.j]
 [5.+1.j 4.+0.j]]


In [4]:
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d=np.empty((5,5))
print(d)

[[6.01347002e-154 6.01347002e-154 7.54951879e-096 5.98147503e-154
  3.13825441e-258]
 [3.98220466e+209 4.83245961e+276 6.01347002e-154 3.35737877e-090
  8.63400231e+140]
 [6.01347002e-154 3.32903917e-090 1.00630255e+141 6.01347002e-154
  7.42400542e-047]
 [5.56732928e+141 6.01347002e-154 8.16133587e-153 3.88834045e+160
  1.16304910e+214]
 [6.01334510e-154 6.01347002e-154 8.03704345e-095 1.05894612e-153
  1.15301226e-259]]


In [10]:
e=np.arange(8)
print(np.shape(e))

(8,)


In [12]:
f=np.array([[1,2,3,4,5,6,7,8,9,10]])
print(np.shape(f))

(1, 10)


In [16]:
g = e.reshape(4,2)
print(g)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
